### ISSUE TITLE
Alexa in Failed State

### ISSUE THREAD

**Issue by goodpunk6** [xtools-at/AssistantPi#10]
**Python 2 & 3 releases (`python2 --version` and `python3 --version`):**
```
Whatever Jessie Lite comes with
```

**Description of problem:**
```
Alexa service is in failed state -


pi@raspberrypi:~ $ sudo systemctl status AlexaPi.service
● AlexaPi.service - Alexa client for all your devices
   Loaded: loaded (/usr/lib/systemd/system/AlexaPi.service; enabled)
   Active: failed (Result: exit-code) since Sat 2017-05-13 21:48:10 UTC; 1min 2s ago
     Docs: https://github.com/alexa-pi/AlexaPi/wiki
  Process: 1017 ExecStart=/usr/bin/python /opt/AlexaPi/src/main.py --daemon (code=exited, status=1/FAILURE)
 Main PID: 1017 (code=exited, status=1/FAILURE)

May 13 21:48:10 raspberrypi python[1017]: surround50:CARD=Device,DEV=0
May 13 21:48:10 raspberrypi python[1017]: surround51:CARD=Device,DEV=0
May 13 21:48:10 raspberrypi python[1017]: surround71:CARD=Device,DEV=0
May 13 21:48:10 raspberrypi python[1017]: iec958:CARD=Device,DEV=0
May 13 21:48:10 raspberrypi python[1017]: dmix:CARD=Device,DEV=0
May 13 21:48:10 raspberrypi python[1017]: dsnoop:CARD=Device,DEV=0
May 13 21:48:10 raspberrypi python[1017]: hw:CARD=Device,DEV=0
May 13 21:48:10 raspberrypi python[1017]: plughw:CARD=Device,DEV=0
May 13 21:48:10 raspberrypi systemd[1]: AlexaPi.service: main process exited, code=exited, status=1/FAILURE
May 13 21:48:10 raspberrypi systemd[1]: Unit AlexaPi.service entered failed state.

```

**Expected:**
```
to not be in a failed state.
```

**Steps to reproduce:**

1. follow instructions to install assistant pi
2. 
3. 

**Traceback (if applicable):**
```

```

**Additional info:**
```
reformatted SD card. copied latest stock image of jessie lite to SD card. installed assistant pi. 
```

**Comment by xtools-at** [comment]
your sound config seems not be right, the setup only applies the default config. Please see the links in the README and adjust your config.yaml according to your audio in- and output devices (`aplay -L && arecord -L`).
Try running AssistantPi in debug-mode (`python /opt/AlexaPi/src/main.py -d`) for the full output, read what the error message says and act accordingly.

**Comment by goodpunk6** [comment]
what was the command to remove and reinstall google manually?

**Comment by xtools-at** [comment]
You can do `sudo bash /opt/AlexaPi/src/scripts/install_assistant.sh` or check out the [contents of that file](https://github.com/xtools-at/AssistantPi/blob/master/src/scripts/install_assistant.sh) to see every single command.

Basically, this should remove and re-install the SDK:
```
cd /opt/AlexaPi/src
sudo rm -rf assistant-sdk-python
sudo git clone https://github.com/xtools-at/assistant-sdk-python.git
cd /opt/AlexaPi/src/assistant-sdk-python
/opt/AlexaPi/env/bin/python -m pip install --upgrade -e ".[samples]"
```

But what are you trying to accomplish? This problem is related to the sound config of AlexaPi, not to Google Assistant SDK.

**Comment by goodpunk6** [comment]
wow! thanks for your script! I went ahead and avoided all of these
headaches by installing jessie with pixel desktop. google authorization was
a breeze as the auth url was always localhost:8080. doing it on the
raspberry pi was so easy I feel terrible for bothering you.

Thanks again for this awesome script!
