### ISSUE TITLE
urllib3 problem

### ISSUE THREAD

**Issue by mcosti** [xtools-at/AssistantPi#14]
Hello. When I try to activate my Google Credentials, this is what I get.
   raise RuntimeError('Requests dependency \'urllib3\' must be version >= 1.21.1, < 1.22!')
RuntimeError: Requests dependency 'urllib3' must be version >= 1.21.1, < 1.22!

I tried to upgrade it to 1.21.1, but failed.

Thank you for your help.

**Comment by bote795** [comment]
same issue... though part of error also says following : 
`"/usr/lib/python3.4/importlib/util.py"`

but my python is 2.7.9 not sure if pip installs are version dependent

**Comment by bote795** [comment]
try runing the following @mcosti 
` sudo /opt/AlexaPi/env/bin/python -m pip install -I urllib3==1.21.1`

fixed it for me.. went into the install script and saw that it created an env so have to install into that env

**Comment by mcosti** [comment]
This worked. Thank you.

**Comment by mcosti** [comment]
Oh. Actually, it worked on the Authentication. But on this:
sudo bash /opt/AlexaPi/src/scripts/install_assistant.sh

Same error.

**Comment by bote795** [comment]
yea that reruns all the installation packages so you need to rerun the command I said, and you only need to run the authentication one (it comes out when you run the command you said). instead of the whole installation

**Comment by xtools-at** [comment]
Sorry, I've been out of town for some days - Glad you found the solution, I'll include this into the installer script!
