### ISSUE TITLE
Suggestion: Simple Status monitoring API

### ISSUE THREAD

**Issue by eouia** [xtools-at/AssistantPi#18]
Thanks for your great Job.

This issue is not for the bug, rather than a suggestion.

I want to use this module for my homebrew project - magic mirror. It has no good input interface except voice or some kinds of sensor. So I believe this voice assistant could be a good option for me. (Of course, I shall make some Alexa Skills or Google Actions for controlling my mirror)

Anyway,
There is a little missing feature to use this module with another program.
It is very difficult to detect this program's working well or not in background process. Is it alive? It might be normally working but just the volume is too low to hear? When on development stage, I can check everything by myself. But after deploying, It's not easy. My main users(my family) wouldn't like if Alexa or Google doesn't answer when they call. 

 I want to monitor this service status by another program. Maybe I could catch the logs. But if you provide a small feature to broadcast signal with simple REST API, It could be more convenient.

It would be simple. 
You just send a tiny Heartbeat signal to pre-configurable(in `config.YAML`??) HTTP endpoint. I will catch the signal and can guess the status of this program by it. 
By example, 
Assuming this URL for the listener.
`http://my.another.server/listen`
And you can send some signals to this API occasionally or on schedules.
when started : POST `{status:'started'}`
when alive, every 1 minutes(if available) : POST `{status:'alive'}`
when hotwords are detected: POST `{status:'actiavted'}`
when Assistant works : POST `{status:'processing'}`
when Assistant fails : POST `{status:'failed'}`
and so on...(I think you don't need a RESPONSE)
...

And I just catch this HTTP REQUEST then use for variable things, like showing status on my mirror or displaying warning on inactive, or using as trigger for other jobs(e.g. rebooting, stop using another mic or speaker)

Could you provide this features? I'm not an expert so I cannot make PULL REQUEST by myself.

**Comment by xtools-at** [comment]
Hi @eouia,
sorry but I can't do this for you.
You can try play around with AlexaPi's pre- and post-interaction hooks. In the `config.yaml`, you'll find `event_commands`, where you can add custom bash commands to be run on certain events. _pre_interaction_ runs before you talk to Alexa/Assistant, _post_interaction_ after it's finished. You could do your web calls here.
Add your own hooks where necessary in the [/src/main.py](https://github.com/xtools-at/AssistantPi/blob/master/src/main.py). 

Let me know how it goes :)

**Comment by eouia** [comment]
Thanks for your reply. I'll close this.
