### ISSUE TITLE
Suggestion: Add spotify connect...

### ISSUE THREAD

**Issue by michaeldeborst** [xtools-at/AssistantPi#22]
Just a suggestion: maybe add Spotify connect and/or mopidy... This would be so awesome to have like your own sonos with voice assistant

**Comment by xtools-at** [comment]
if it's added to either AlexaPi or Google Assistant SDK (the 2 projects AssistantPi is built by), I'd happy to merge to it :) Maybe you could place your request there.

**Comment by xtools-at** [comment]
#28
