### ISSUE TITLE
Add additional subprocess python

### ISSUE THREAD

**Issue by Mcgurk125** [xtools-at/AssistantPi#24]
Where would be the best place to call a python script just before the audio outs? I have an infared blaster and a python script I use to set the audio input on a surround system. I would need to run this script just before the audio out and another after finishing (to change audio input back)

**Comment by xtools-at** [comment]
check the [config.yaml](https://github.com/xtools-at/AssistantPi/blob/master/src/config.template.yaml) for the *event_commands* section. you can add shell commands here, which get executed at certain events (e.g.  *pre_interaction* or *post_ interaction*). if you already installed AssistantPi, this file lives in `/etc/opt/AlexaPi/config.yaml`

check [main.py](https://github.com/xtools-at/AssistantPi/blob/master/src/main.py) for where and how those events are triggered.
