### ISSUE TITLE
Crash while initializing Google Assistant

### ISSUE THREAD

**Issue by claudioita** [xtools-at/AssistantPi#4]
"Hello" is spoken almost immediately

The blink sound (I think of initializing Google) it takes long, like few minutes, and is not working

pi@raspberrypi:~ $ python /opt/AlexaPi/src/main.py
2017-05-08 18:27:35 INFO: Checking Internet Connection ...
2017-05-08 18:27:36 INFO: Connection OK
2017-05-08 18:27:36 INFO: AVS token: Requesting a new one
2017-05-08 18:27:37 INFO: AVS token: Obtained successfully
sox WARN mp3-util: MAD lost sync
sox WARN alsa: under-run
sox WARN alsa: under-run
sox WARN alsa: under-run
sox WARN alsa: under-run
sox WARN alsa: under-run
sox WARN alsa: under-run
sox WARN alsa: under-run
sox WARN alsa: under-run
sox WARN alsa: under-run
sox WARN alsa: under-run
sox WARN alsa: under-run
sox WARN alsa: under-run
sox WARN alsa: under-run
sox WARN alsa: under-run
sox WARN alsa: under-run
sox WARN alsa: under-run
sox WARN alsa: under-run
sox WARN alsa: under-run
sox WARN alsa: under-run
sox WARN alsa: under-run
sox WARN alsa: under-run
sox WARN alsa: under-run
sox WARN alsa: under-run
sox WARN alsa: under-run
sox WARN alsa: under-run
sox WARN alsa: under-run
sox WARN alsa: under-run
sox WARN alsa: under-run
sox WARN alsa: under-run
sox WARN alsa: under-run
sox WARN alsa: under-run
sox WARN alsa: under-run
sox WARN alsa: under-run
sox WARN alsa: under-run
sox WARN alsa: under-run
sox WARN alsa: under-run
sox WARN alsa: under-run
INFO:root:Connecting to embeddedassistant.googleapis.com
INFO:root:Recording audio request.
INFO:root:End of audio request detected
INFO:root:Finished playing assistant response.
INFO:root:Assistant conversation finished.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/AlexaPi/src/alexapi/triggers/pocketsphinxtrigger.py", line 61, in thread
    inp = alsaaudio.PCM(alsaaudio.PCM_CAPTURE, alsaaudio.PCM_NORMAL, self._config['sound']['input_device'])
ALSAAudioError: Device or resource busy [plughw:CARD=USB,DEV=0]

**Comment by claudioita** [comment]
is the above normal behaviour?

**Comment by xtools-at** [comment]
> is the above normal behaviour?

no it's not, seems that the Google-sound is blocking the audio resources for the Assistant SDK. I'll have a look into this on the weekend.

**Comment by claudioita** [comment]
it should say "Hello" (Alexa) and blink sound (Google Assistant) almost together, correct?

**Comment by xtools-at** [comment]
no, the _hello_ is just the sign that AlexPi is ready.
the Google-sound plays when the Google-hotword has been recognized, the connection to Google servers is established and it starts recording. This usually takes 2-3 seconds after you've said the hotword.

**Comment by xtools-at** [comment]
Hi there,
I've re-written a big part of AssistantPi, this shouldn't be an issue anymore. Please re-open the ticket if you're still experiencing this problem.

Please run
```
cd /opt/AlexaPi
sudo git pull
sudo /opt/AlexaPi/src/scripts/setup.sh
```
and do the setup again, including Auth with Google and Amazon.
