### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by goodpunk6** [xtools-at/AssistantPi#6]
**Python 2 & 3 releases (`python2 --version` and `python3 --version`):**
```
Whatever comes with Raspbian Lite
```

**Description of problem:**
```
When i try to authorize Google stuff, I'm brought to a website that asks me to Allow google's api (i think). When I click allow, nothing happens. I'm brought to a grey page that simply says connection refused. picture here - https://dl.dropboxusercontent.com/s/zfuir6sri5hcxms/chrome_2017-05-12_22-54-50.png

![chrome_2017-05-12_22-54-50 1](https://cloud.githubusercontent.com/assets/15090661/26021978/b53dff72-3766-11e7-9ea2-13cfbf54b6f2.png)

```

**Expected:**
```
to authorize.
```

**Steps to reproduce:**

1. attempt to authenticate with google
2. click allow
3. look at connection refused page.

**Traceback (if applicable):**
```

```

**Additional info:**
```
I have a raspberry pi 3 that has nothing else but Assistant Pi on it.
```

**Comment by xtools-at** [comment]
hi, please provide more information - is it sure the google auth or is it the amazon authorization? please paste the lines that came before this in your terminal and provide the url you are trying to open.

Sidenote: I'm re-writing AssistantPi right now, as I was experiencing some painful bugs. Better wait a few days for the new release.

**Comment by goodpunk6** [comment]
I had to start the authorization manually. 

```
pi@raspberrypi:~ $ /opt/AlexaPi/env/bin/python -m googlesamples.assistant.auth_helpers --client-secrets /home/pi/Downloads/client_secret.json
Please visit this URL to authorize this application: https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=1071494548268-9bf77r8k5kkd3hts6jpij5h62hdreqh3.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fassistant-sdk-prototype&state=cnfplcb0wjZqT7CCo9bN9QOzzSDr17&access_type=offline

```

**Comment by xtools-at** [comment]
I can open the link without problems, no "Connection refused" - maybe you could try to disable your Adblocker or try another Browser.

**Comment by goodpunk6** [comment]
I did disable my firewall. I'll try another browser

**Comment by goodpunk6** [comment]
i disabled my firewall and tried 3 different browsers. I still get connection refused. This is all with the updated script

**Comment by goodpunk6** [comment]
I formatted and reinstalled at least 6 times. everytime, connection refused.

**Comment by xtools-at** [comment]
It has nothing to do with AssistantPi that you can't open Google's Auth link, there's something about your setup/network... plz try open the link on another computer, on your phone or any other device that has a Browser - I can't help you with this

**Comment by goodpunk6** [comment]
i have tried on 3 different networks. still happens. wtf? please reopen issue. not my networks.

**Comment by xtools-at** [comment]
Seriously, I can't help here. The [link](https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=1071494548268-9bf77r8k5kkd3hts6jpij5h62hdreqh3.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fassistant-sdk-prototype&state=cnfplcb0wjZqT7CCo9bN9QOzzSDr17&access_type=offline) you've posted works fine:
[![g.jpg](https://s12.postimg.org/uej0laznx/image.jpg)](https://postimg.org/image/4iza23xu1/)

Additionally, I haven't altered the Authorization with Google API, it's 100% the same as in the SDK. If you can't get it to work, please file an issue in [Google's Assistant SDK Repository](https://github.com/googlesamples/assistant-sdk-python).

**Comment by goodpunk6** [comment]
Ok thanks!
