### ISSUE TITLE
running the setup script downloads seemingly unnecessary packages

### ISSUE THREAD

**Issue by vmarks** [xtools-at/AssistantPi#9]
Thank you for reporting an issue with **AssistantPi**.

Please make sure you've updated to the latest version using
```
sudo /opt/AlexaPi/src/scripts/update.sh
```
This updates both AssistantPi and the [tweaked Assistant SDK](https://github.com/xtools-at/assistant-sdk-python) without having you to go through the installation process again.

Please check out these resources before submitting an issue:
- [AlexaPi Wiki](https://github.com/alexa-pi/AlexaPi/wiki/)
- [AlexaPi Debugging](https://github.com/alexa-pi/AlexaPi/wiki/Debugging/)
- [AlexaPi Audio debugging](https://github.com/alexa-pi/AlexaPi/wiki/Audio-setup-&-debugging)
- [Google Assistant Troubleshooting](https://developers.google.com/assistant/sdk/prototype/getting-started-pi-python/troubleshooting)
- [Google Assistant Audio Configuration](https://developers.google.com/assistant/sdk/prototype/getting-started-pi-python/configure-audio)

In order to help troubleshooting, be sure to include the following information:

**Python 2 & 3 releases (`python2 --version` and `python3 --version`):**
```

```

**Description of problem:**
```

As I run the setup.sh script, I see it downloading and unpacking x11-common, along with libdvdread. Why?

```

**Expected:**
```
Do not download packages that are not required.
```

**Steps to reproduce:**

1. 
2. 
3. 

**Traceback (if applicable):**
```

```

**Additional info:**
```

```

**Comment by xtools-at** [comment]
AssistantPi is built upon AlexaPi. The packages might be dependencies of dependencies, I won't start taking AlexaPi apart, there's other work to do with AssistantPi
